### ISSUE TITLE
Horizontal intersection view on real-time view is truncated 

### ISSUE THREAD

**Issue by mkasztelnik** [ismop/eitwid#124] opened 2016-08-22 06:07 UTC
![poziomy_prekroj](https://cloud.githubusercontent.com/assets/1265430/17845095/79cc156a-683f-11e6-98de-b0fab6949299.png)

**Comment by mkasztelnik** [comment] 2016-08-22 06:11
This bug can be connected with new neosentio sensors and profiles registered by @nowakowski lately.

**Comment by dharezlak** [comment] 2016-08-22 12:58
OK, finally the cause has been found. The end section (north round one) has been assigned two profiles and stopped being profile-less which breaks UI processing. Reported https://github.com/ismop/dap/issues/150 to reassign the profiles to the neighbouring straight ones.

**Closed** 2016-08-22 14:44 UTC
Labels: bug
